image: opensuse/tumbleweed
 
before_script:
  - zypper in -y texinfo make tar
  - zypper in -y 'tex(beamer.cls)' 'tex(bbm.sty)' 'tex(capt-of.sty)' 'tex(textpos.sty)' 'tex(czech.ldf)'
 
stages:
  - build
 
build-pdfs:
  stage: build
  script:
    - make || cat */*.log
 
  # The files which are to be made available in GitLab
  # pdf are results
  artifacts:
    paths:
      - "*/*.pdf"
