image: opensuse/tumbleweed
 
before_script:
  - zypper in -y texinfo make
  - zypper in -y 'tex(beamer.cls)' 'tex(bbm.sty)' 'tex(capt-of.sty)'
 
stages:
  - build
 
build-pdfs:
  stage: build
  script:
    - make || { cat */*.log ; exit 1 }
 
  # The files which are to be made available in GitLab
  # pdf are results
  artifacts:
    paths:
      - "*/*.pdf"
