image: opensuse/tumbleweed
 
before_script:
  - zypper in -y texinfo make
  - zypper in -y 'tex(beamer.cls)'
 
stages:
  - build
 
build-pdfs:
  stage: build
  script:
    - make
 
  # The files which are to be made available in GitLab
  # pdf are results ; log are errors from tex
  artifacts:
    paths:
      - "*/*.pdf"
      - "*/*.log"
